project:
  type: website
  post-render: randomizeFooterQuote.py

website:
  title: "ddanieltan.com"
  site-url: https://www.ddanieltan.com
  repo-url: https://github.com/ddanieltan/ddanieltan.com
  twitter-card: true
  open-graph: true
  navbar:
    right:
      - about.qmd
      - icon: github
        aria-label: github
        href: https://github.com/ddanieltan
      - icon: linkedin
        aria-label: linkedin
        href: https://www.linkedin.com/in/ddanieltan/
  page-footer: "We are not given a short life but we make it short, we are not ill-supplied but wasteful of it. Life is long if you know how to use it. - Seneca"
  google-analytics: "G-BQGXLNCBHY"
format:
  html:
    theme: 
      - litera
      - custom.scss
    smooth-scroll: true
    # code-tools:
      # source: true



